security:
    enable_authenticator_manager: true
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
    providers:
        backend_users:
            memory:
                users:
                    test@eurodk.com: { password: admin, roles: ['ROLE_USER'] }
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js|html)/
            security: false
        login:
            pattern: ^/login
            stateless: true
            json_login:
                check_path: login
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
        api:
            stateless: true
            jwt: ~

    access_control:
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/,      roles: IS_AUTHENTICATED_FULLY }
